apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-nextcloud-hpa-cpu
  namespace: app-nextcloud
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: <name of the nextcloud deployment>
  minReplicas: 1
  maxReplicas: 4
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 25   
        periodSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 4
        periodSeconds: 10
      - type: Percent
        value: 25
        periodSeconds: 10
      selectPolicy: Max
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80