apiVersion: v1
kind: Service
metadata:
  annotations:
    #Persistent Session Cookie Settings for the loadbalancer service
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: dep
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
